# Generated by Django 4.2.13 on 2024-05-26 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('rooms', models.DecimalField(decimal_places=1, max_digits=10)),
                ('size', models.IntegerField()),
                ('reporter', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=100)),
                ('internalId', models.CharField(max_length=100, unique=True)),
                ('src', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('insertedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('interval', models.IntegerField(default=600)),
                ('last_sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporters', models.JSONField(blank=True, default=list, null=True)),
                ('sizes', models.JSONField(blank=True, default=list, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('districts', models.JSONField(blank=True, default=list, null=True)),
                ('property_types', models.JSONField(blank=True, default=list, null=True)),
                ('rooms', models.JSONField(blank=True, default=list, null=True)),
                ('isReady', models.BooleanField(default=False)),
            ],
        ),
    ]
