# Generated by Django 4.2.13 on 2024-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
