# Generated by Django 4.2.13 on 2024-05-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='chat_id',
            new_name='user_id',
        ),
    ]
