# Generated by Django 4.2.13 on 2024-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apartment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='published',
            field=models.CharField(max_length=100),
        ),
    ]
